

###
POST http://localhost:8899/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "mobile": "0898765432",
  "email": "donkey@popmail.com",
  "firstName": "Donkey",
  "lastName": "Kikikiki",
  "password": "mydonkey123456",
  "confirmPassword": "mydonkey123456"
}

###
# Login API
POST http://localhost:8899/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "identity": "somsak@xmail.com",
  "password": "mysomsak123456"
}


###
GET http://localhost:8899/api/auth/me HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsImlhdCI6MTc1MDkwOTA0NywiZXhwIjoxNzUyMjA1MDQ3fQ.YR93Q3lu38KCWtpoI_YxgIbPdMaWxIooWL-HeCKTLiY

###
POST http://localhost:8899/api/post HTTP/1.1
Content-Type: application/json

{
  "message": "Hello, CC20"
  # "message": "Hello, CC21"
}

###

GET http://localhost:8899/api/auth/men HTTP/1.1